using System.Text;

namespace SquidStd.Generators.Events;

internal static class EventListenerSourceBuilder
{
    public static string Build(IReadOnlyList<EventListenerCandidate> candidates)
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace SquidStd.Generators.Events;");
        builder.AppendLine();
        builder.AppendLine("public static class GeneratedEventListenerRegistrationExtensions");
        builder.AppendLine("{");
        builder.AppendLine(
            "    public static global::DryIoc.IContainer RegisterGeneratedEventListeners(this global::DryIoc.IContainer container)"
        );
        builder.AppendLine("    {");

        for (var i = 0; i < candidates.Count; i++)
        {
            builder.Append(
                "        global::SquidStd.Abstractions.Extensions.Events.RegisterEventListenerExtension.RegisterEventListener<"
            );
            builder.Append(candidates[i].EventTypeName);
            builder.Append(", ");
            builder.Append(candidates[i].ListenerTypeName);
            builder.AppendLine(">(container);");
        }

        builder.AppendLine();
        builder.AppendLine("        return container;");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }
}
