using System.Text;

namespace SquidStd.Generators.ConsoleCommands;

internal static class ConsoleCommandSourceBuilder
{
    public static string Build(IReadOnlyList<ConsoleCommandRegistrationCandidate> candidates)
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace SquidStd.Generators.ConsoleCommands;");
        builder.AppendLine();
        builder.AppendLine("public static class GeneratedConsoleCommandRegistrationExtensions");
        builder.AppendLine("{");
        builder.AppendLine(
            "    public static global::DryIoc.IContainer RegisterGeneratedConsoleCommands(this global::DryIoc.IContainer container)"
        );
        builder.AppendLine("    {");

        for (var i = 0; i < candidates.Count; i++)
        {
            var candidate = candidates[i];

            builder.Append("        global::DryIoc.Registrator.Register<");
            builder.Append(candidate.ExecutorTypeName);
            builder.AppendLine(">(container, global::DryIoc.Reuse.Singleton);");
            builder.AppendLine(
                "        global::DryIoc.Registrator.RegisterInitializer<global::SquidStd.ConsoleCommands.Interfaces.ICommandSystemService>("
            );
            builder.AppendLine("            container,");
            builder.AppendLine("            static (commandSystem, resolverContext) =>");
            builder.AppendLine("            {");
            builder.Append("                var executor = global::DryIoc.Resolver.Resolve<");
            builder.Append(candidate.ExecutorTypeName);
            builder.AppendLine(">(resolverContext);");
            builder.Append("                commandSystem.RegisterCommand(");
            builder.Append(FormatStringLiteral(candidate.CommandName));
            builder.Append(", executor.ExecuteAsync, ");
            builder.Append(
                candidate.Description.Length == 0
                    ? "executor.Description"
                    : FormatStringLiteral(candidate.Description)
            );
            builder.AppendLine(");");
            builder.AppendLine("            }");
            builder.AppendLine("        );");
        }

        builder.AppendLine();
        builder.AppendLine("        return container;");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static string FormatStringLiteral(string value)
        => "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
