using System.Globalization;
using System.Text;

namespace SquidStd.Generators.Services;

internal static class StdServiceSourceBuilder
{
    public static string Build(IReadOnlyList<StdServiceRegistrationCandidate> candidates)
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace SquidStd.Generators.Services;");
        builder.AppendLine();
        builder.AppendLine("public static class GeneratedStdServiceRegistrationExtensions");
        builder.AppendLine("{");
        builder.AppendLine(
            "    public static global::DryIoc.IContainer RegisterGeneratedStdServices(this global::DryIoc.IContainer container)"
        );
        builder.AppendLine("    {");

        for (var i = 0; i < candidates.Count; i++)
        {
            builder.Append(
                "        global::SquidStd.Abstractions.Extensions.Services.RegisterStdServiceExtension.RegisterStdService<"
            );
            builder.Append(candidates[i].ServiceTypeName);
            builder.Append(", ");
            builder.Append(candidates[i].ImplementationTypeName);
            builder.Append(">(container, ");
            builder.Append(candidates[i].Priority.ToString(CultureInfo.InvariantCulture));
            builder.AppendLine(");");
        }

        builder.AppendLine();
        builder.AppendLine("        return container;");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }
}
