using System.Text;

namespace SquidStd.Generators.Workers;

internal static class JobHandlerSourceBuilder
{
    public static string Build(IReadOnlyList<JobHandlerRegistrationCandidate> candidates)
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace SquidStd.Generators.Workers;");
        builder.AppendLine();
        builder.AppendLine("public static class GeneratedJobHandlerRegistrationExtensions");
        builder.AppendLine("{");
        builder.AppendLine("    public static global::DryIoc.IContainer RegisterGeneratedJobHandlers(this global::DryIoc.IContainer container)");
        builder.AppendLine("    {");

        for (var i = 0; i < candidates.Count; i++)
        {
            builder.Append("        global::SquidStd.Workers.Extensions.WorkersRegistrationExtensions.AddJobHandler<");
            builder.Append(candidates[i].HandlerTypeName);
            builder.AppendLine(">(container);");
        }

        builder.AppendLine();
        builder.AppendLine("        return container;");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }
}
