using System.Globalization;
using System.Text;

namespace SquidStd.Generators.Config;

internal static class ConfigSectionSourceBuilder
{
    public static string Build(IReadOnlyList<ConfigSectionRegistrationCandidate> candidates)
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace SquidStd.Generators.Config;");
        builder.AppendLine();
        builder.AppendLine("public static class GeneratedConfigSectionRegistrationExtensions");
        builder.AppendLine("{");
        builder.AppendLine(
            "    public static global::DryIoc.IContainer RegisterGeneratedConfigSections(this global::DryIoc.IContainer container)"
        );
        builder.AppendLine("    {");

        for (var i = 0; i < candidates.Count; i++)
        {
            builder.Append(
                "        global::SquidStd.Abstractions.Extensions.Config.RegisterConfigSectionExtension.RegisterConfigSection<"
            );
            builder.Append(candidates[i].ConfigTypeName);
            builder.Append(">(container, ");
            builder.Append(FormatStringLiteral(candidates[i].SectionName));
            builder.Append(", priority: ");
            builder.Append(candidates[i].Priority.ToString(CultureInfo.InvariantCulture));
            builder.AppendLine(");");
        }

        builder.AppendLine();
        builder.AppendLine("        return container;");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static string FormatStringLiteral(string value)
        => "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
