using System.Text;

namespace SquidStd.Generators.Scripting.Lua;

internal static class ScriptModuleSourceBuilder
{
    public static string Build(IReadOnlyList<ScriptModuleRegistrationCandidate> candidates)
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace SquidStd.Generators.Scripting.Lua;");
        builder.AppendLine();
        builder.AppendLine("public static class GeneratedScriptModuleRegistrationExtensions");
        builder.AppendLine("{");
        builder.AppendLine(
            "    public static global::DryIoc.IContainer RegisterGeneratedScriptModules(this global::DryIoc.IContainer container)"
        );
        builder.AppendLine("    {");

        for (var i = 0; i < candidates.Count; i++)
        {
            builder.Append(
                "        global::SquidStd.Scripting.Lua.Extensions.Scripts.AddScriptModuleExtension.RegisterScriptModule<"
            );
            builder.Append(candidates[i].ScriptModuleTypeName);
            builder.AppendLine(">(container);");
        }

        builder.AppendLine();
        builder.AppendLine("        return container;");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }
}
